name: luna_project
dependencies:
  - python=3.10.4
  - pip=22.2.2
  - psycopg2
  - pip:
      - django==4.1.1
      - djangorestframework==3.14.0
      - djangorestframework_simplejwt==5.2.2
      - Pillow==9.2.0
      - flake8==5.0.4
      - gunicorn==20.1.0
      - PyJWT==2.6.0
      - django-cors-headers
      - asgiref==3.5.2
      - pycodestyle==2.9.1
      - pytz==2022.5




