name: luna_project
dependencies:
  - python=3.10.4
  - pip=22.2.2
  - psycopg2
  - pip:
      - django==4.1.1
      - djangorestframework==3.14.0
      - djangorestframework_simplejwt==5.2.2
      - Pillow==9.2.0
      - flake8==5.0.4
      - gunicorn
      - django-cors-headers


